site_name: Adam Stone Digital Portfoio
nav:
    - Home: index.md
    - About: about.md
    - Projects:
      - "RhythmLinkÂ®":
        - Overview: projects/rhythm-link/rhythm-link.md
        - "EEGs":
          - Overview: projects/rhythm-link/eeg-testing-device/overview.md
theme: 
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon/favicon.ico
  palette:
    primary: blue
    accent: orange
markdown_extensions:
  - attr_list
plugins:
    - search
    - mermaid2